package wsb.bugtracker.models;

public enum AuthorityName {
    ROLE_CREATE_USER, ROLE_DELETE_USER, ROLE_EDIT_USER, ROLE_LIST_USER,
    ROLE_CREATE_PROJECT, ROLE_DELETE_PROJECT, ROLE_EDIT_PROJECT, ROLE_VIEW_PROJECT,
    ROLE_CREATE_ISSUE, ROLE_DELETE_ISSUE, ROLE_EDIT_ISSUE, ROLE_VIEW_ISSUE,
    ROLE_ADMIN, ROLE_EDIT_ACCOUNT
}
